name:                zio
version:             0.1.0.2
github:              "bbarker/haskell-zio"
license:             MPL-2.0
author:              "Brandon Elam Barker"
maintainer:          "brandon.barker@gmail.com"
copyright:           "2020 Brandon Elam Barker"

extra-source-files:
- README.md
- shell.nix
- package-shell.nix
- ChangeLog.md

extra-doc-files:
- docs/BuildNotes.md

# Metadata used when publishing your package
synopsis:            App-centric Monad-transformer based on Scala ZIO (UIO + ReaderT + ExceptT).
category:            Control

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bbarker/haskell-zio#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2.2 && < 2.3
- transformers >= 0.5.6 && < 0.6
- unexceptionalio >= 0.5.1 && < 0.6
- unexceptionalio-trans >= 0.5.1 && < 0.6

library:
  source-dirs: src
  ghc-options:
  - -Wall -Wtabs -Wincomplete-record-updates

tests:
  zio-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zio
